### ISSUE TITLE
Way to keep code in full view for code blocks with shadowed code

### ISSUE THREAD

**Issue by Arteneko** [adonisjs/v5-docs#100]
Some code blocks have shadowed parts (e.g. to highlight some certain part), making it annoying to read if you'd just like to have the whole block without shadowing.

Could there be a toggle to disable shadowing? Thanks

Example: 
![A code block with several lines of code. One of them is visible, the rest is shadowed into the background, making it very hard to see.](https://user-images.githubusercontent.com/23583792/142689014-e9a3a04e-c129-4830-81b2-ecdb6c0391e3.png)

**Comment by thetutlage** [comment]
Just hover over the code block.

**Comment by Arteneko** [comment]
This answer is completely off-topic.
The need to hover *is the issue*.

Anyways, maybe I'll grab a bit of time to fiddle with the docs for that today.

**Comment by thetutlage** [comment]
Your expectation is subjective. What you find as "annoying", others find as "helpful".

**Comment by Arteneko** [comment]
So I guess you techbros don't give a fuck about accessibility, as usual.

You know, the point of *a setting* is to allow users to have their preferred and most comfortable settings in place. 

Not force a moronic and inaccessible choice in place, a choice that would only work for some people.
