### ISSUE TITLE
Improve type information at Wildcard

### ISSUE THREAD

**Issue by brkn** [adonisjs/v5-docs#131]
Documentation for [Custom messages with wildcard callback](https://docs.adonisjs.com/guides/validator/custom-messages#wildcard-callback) is missing types for it's parameters.

I've assumed types are correct at [MessageBag](https://github.com/adonisjs/validator/blob/develop/src/MessagesBag/index.ts#L70).

#### Change proposal on the code example

```ts
const wildCardError = (
  field: string,
  rule: string,
  arrayExpressionPointer?: string,
  options?: any
) => {
  return `${rule} validation error on ${field}`
}

{
  messages: {
    '*': wildCardError,
    'username.required': 'Username is required to sign up',
  }
}
```

**Comment by thetutlage** [comment]
If you put the callback right within the messages object, you will get types automatically, without being explicit about them.

```ts
messages: {
  '*': (field, rule, arrayExpressionPointer, options) {

  }
}
```

With that being said. It is technically valid to extract the method to a different file or maybe at the top in the same file. However, documentation cannot show all the styles, as it makes the docs verbose.

**Comment by brkn** [comment]
But the validator classes doesn't have this type information, [not in the documentation either](https://docs.adonisjs.com/guides/validator/introduction#validator-classes). I felt the need to search the codebase itself instead of reading from the document, is there another way I can help to improve this experience?

<img width="532" alt="Screen Shot 2022-03-14 at 15 44 00" src="https://user-images.githubusercontent.com/32255826/158174536-6abd9aa5-5ed9-452f-942e-dc306ab93399.png">

**Comment by thetutlage** [comment]
Can you please share how this can be improved? Or maybe just send a PR with the improvement :)

**Comment by brkn** [comment]
I can think 2 solutions for the class validators

1. Import the `CustomMessages` interface at the example code in the [validator classes documentation](https://docs.adonisjs.com/guides/validator/introduction#validator-classes)
  ```ts
  import { schema, CustomMessages } from '@ioc:Adonis/Core/Validator'
  import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'

  export default class CreateUserValidator {
    constructor (protected ctx: HttpContextContract) {
    }

    public schema = schema.create({
    })

    public messages: CustomMessages = {}
  }
  ```

2. Introduce an interface for validator class itself, then change the example to have `implements Validator`
```ts
export default class CreateUserValidator implements Validator{
// ...
}
```

**Comment by thetutlage** [comment]
Making the validator implement an interface doesn't sound intuitive to me. However, we can document that the messages property can use the `CustomMessages` type.
