### ISSUE TITLE
Missing dcoumentation - String related `escape` and `trim` rules 

### ISSUE THREAD

**Issue by brkn** [adonisjs/v5-docs#143]
After the latest release [String documentation](https://github.com/adonisjs/docs.adonisjs.com/blob/d86b5f1553f193ba89c7af7a76b4edcd09cafe68/content/reference/validator/schema/string.md) is missing escape and trim rules.

**Comment by Barbapapazes** [comment]
Now, you can find there here
- [escape](https://docs.adonisjs.com/reference/validator/rules/escape)
- [trim](https://docs.adonisjs.com/reference/validator/rules/trim)

**Comment by brkn** [comment]
Fixed at https://github.com/adonisjs/docs.adonisjs.com/commit/df62a2af923c34e0cdf037e87859a295bd855667
