### ISSUE TITLE
Documentation for redirectToUrl seems to be outdated

### ISSUE THREAD

**Issue by leonardk1** [adonisjs/v5-docs#147]
I was reading through the documentation for `redirectToUrl` ->  https://docs.adonisjs.com/guides/routing#redirecttourl

and when I tried to test it out it does not work.  I found with the help of VSCode that what works is `redirectToPath` . 

was `redirectToUrl` depracated in favour of `redirectToPath` ? If so, then I think a change should be reflected in the documentation.
I can put in a PR, if it is fine

**Comment by thetutlage** [comment]
Ohh yes. The docs needs to be updated. Please share a PR :)
