### ISSUE TITLE
`this.defer` does't work as expected in migrations

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/v5-docs#148]
I'm creating a dictionary table. Immediately after creation, it must be filled with certain static data. I take an [example from the documentation](https://docs.adonisjs.com/guides/database/migrations#performing-other-database-operations), but it doesn't work:

```ts

this.defer(async (db) => {
      const users = await db.select('*').from('users') // TS2339: Property 'select' does not exist on type 'QueryClientContract'.
      await Promise.all(users.map((user) => {
        return db
          .table('user_emails')
          .insert({ user_id: user.id, email: user.email })
      }))
    })
```

And runtime error:
```node
[ error ]  db.select is not a function
```

## Package version
    "@adonisjs/core": "5.7.5",
    "@adonisjs/lucid": "17.2.0",

## Node.js and npm version
8.3.1

**Comment by thetutlage** [comment]
Seems like an issue in the docs. It should be `db.from('users').select('*')`. Can you please send a PR to fix the docs?
