### ISSUE TITLE
Global transactions documentation missing `await` keyword

### ISSUE THREAD

**Issue by estalaPaul** [adonisjs/v5-docs#153]
In the [global transactions](https://docs.adonisjs.com/guides/testing/introduction#global-transactions) documentation, I think the cleanup function should be an async function and should have the await keyword.

Currently, it is `return () => Database.rollbackGlobalTransaction()`, I think it should be: `return async () => await Database.rollbackGlobalTransaction()`, since the `rollbackGlobalTransaction()` function returns a promise. 

I can open a PR, just wanted to make sure this wasn't intentional.

**Comment by thetutlage** [comment]
When you return a promise, then the surrounding function can skip the `async` keyword. You can learn more about it here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
