### ISSUE TITLE
[official doc bug] Testing upload image example seems out of date

### ISSUE THREAD

**Issue by weretyczx** [adonisjs/v5-docs#155]
Official spec example from here [link](https://docs.adonisjs.com/guides/testing/http-tests#file-uploads) seems not to work,

running version :  "@adonisjs/core": "^5.6.0"

it dose not have `file.createPng('1mb')` method and `fakeDrive.hasFile()` method,
and if follow the `import { file } from '@ioc:Adonis/Core/Helpers'` 
it can get a new `file.generatePng()` method there, but as the same time `.file('avatar', fakeAvatar)` will get fail because of the type error

hoping the team can update the new doc to help people get into the adonis more easily.

**Comment by thetutlage** [comment]
Thanks for reporting. Can you create a PR for the same?

**Comment by weretyczx** [comment]
Surely if I can, but the problem is I'm a rookie in Adonis and don't know the way to wrap the
fake image from `file.generatePng()` to the type `MultipartFile`, 
and make httpClient accept the file upload.

And I am stuck here now. 😂
