### ISSUE TITLE
Driver config: mysql2

### ISSUE THREAD

**Issue by careless10** [adonisjs/v5-docs#166]
On the documentation it says to install the following
```
npm i mysql2
```

but it says to use it 
```
mysql: {
  client: 'mysql',
  connection: {
    host: Env.get('MYSQL_HOST'),
    port: Env.get('MYSQL_PORT'),
    user: Env.get('MYSQL_USER'),
    password: Env.get('MYSQL_PASSWORD', ''),
    database: Env.get('MYSQL_DB_NAME'),
  },
  migrations: {
    naturalSort: true,
  },
  healthCheck: false,
  debug: false,
}
```

i am not quite sure if this is a bug or its supposed to work that way, i changed the client: 'mysql' to 'mysql2' and it worked, could you confirm?
this should solve mysql 8.* issues

**Comment by thetutlage** [comment]
Setting both `mysql` and `mysql2` should work. Just make sure to remove the `mysql` dependency from your project and then `mysql2` will be used automatically even when the client is set to `mysql`

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
