### ISSUE TITLE
Wrong documentation for database driver config

### ISSUE THREAD

**Issue by ricardoaranha96** [adonisjs/v5-docs#174]
### Package version

5.8.4

### Describe the bug

Link of documentation: https://docs.adonisjs.com/guides/database/introduction#drivers-config

The documentation guides us to install the package mysql2 but in the config example the client used is mysql. After I changed it to mysql2 the config started to work.

Also, the code generated by node ace configure @adonisjs/lucid generates a file with a comment that instructs to install mysql instead of mysql2.

**Comment by RomainLanz** [comment]
Hey @ricardoaranha96! 👋🏻 

I have fixed the missing documentation, and this PR https://github.com/adonisjs/lucid/pull/871 did the generated files.
