### ISSUE TITLE
fix: withCount exemple is uncorrect

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/v5-docs#177]
### Package version

@adonisjs/lucid:18.1.0

### Describe the bug

[In this page](https://docs.adonisjs.com/reference/orm/query-builder#withcount), the withCount exemple return a key in camelCase but [reading the code](https://github.com/adonisjs/lucid/blob/develop/src/Orm/QueryBuilder/index.ts#L550), it should be in snake_case!

**Comment by thetutlage** [comment]
It was a docs issue. Thanks for the PR :)
