### ISSUE TITLE
Drive documentation references both `serveAssets` and `serveFiles`

### ISSUE THREAD

**Issue by mattkenefick** [adonisjs/v5-docs#180]
### Package version

latest

### Describe the bug

Drive documentation seems to reference a config variable called `serveAssets` and `serveFiles` interchangeably. In my code, it's defaulted to `serveFiles` so it seems like the `serveAssets` may be incorrect.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/149809/186188439-20803fe8-4813-402a-93af-4084ef6c200e.png">

**Comment by thetutlage** [comment]
Yup, its `serveFiles`. Can you please create a PR for the fix?
