### ISSUE TITLE
Query Scopes Documentation

### ISSUE THREAD

**Issue by nashton109** [adonisjs/v5-docs#2]
Documentation of `Query Scopes` - https://docs.adonisjs.com/guides/models/query-scopes appears to be incorrect. 

The `ModelQueryBuilderContract` does not appear to have a function called `withScopes`, after looking through the tests, it appears it should be `apply`

e.g.

```ts
Post
    .query()
    .withScopes((scopes) => scopes.published())
```

should be 

```ts
Post
    .query()
    .apply((scopes) => scopes.published())
```

It is correct in the reference page - https://docs.adonisjs.com/reference/orm/query-builder#apply

**Comment by RomainLanz** [comment]
Hey @nashton109! 👋 

The function `withScopes` was added [7 days ago](https://github.com/adonisjs/lucid/commit/039defb137054b861b1dc010ab9a71ec153a3dba).

The documentation was wrong back then, but now It is correct! 😋 
I am going to update the reference page for those changes.
