### ISSUE TITLE
Documentation includes features that haven't been released yet.

### ISSUE THREAD

**Issue by joshfoskett** [adonisjs/v5-docs#201]
### Package version

N/A

### Describe the bug

As a developer, I would expect the documentation on "docs.adonisjs.com" to reflect what is currently possible, and not documentation for features that have yet to be released.

For instance, this is currently not possible:
https://docs.adonisjs.com/guides/testing/introduction#truncate-database-after-each-run-cycle

It wasn't until after updating Adonis and searching around did I figure out that it's still a feature sitting in the develop branch of `adonisjs/lucid`, and not something that is currently available to me.

Just thought I'd throw this out there, in the hopes that this is taken into consideration in the future, for a better developer experience. I'm also not sure if this something is already being considered and this slipped by, or if there's just no formal process for ensuring that the feature is available before it lands on the docs.

**Comment by RomainLanz** [comment]
Hey @joshfoskett! 👋🏻 

Thanks for the heads up.
This feature hasn't been released yet, but it was documented. It should be fixed later today.

It was an error on our side. I shouldn't have merged the documentation PR before the release 😃
