### ISSUE TITLE
v5 algolia search points to v6 results

### ISSUE THREAD

**Issue by carlmathisen** [adonisjs/v5-docs#239]
### Describe the bug

Hi guys,

Thank you for the great work on v6! However the v5 docs are pointing to v6 results. See the link in bottom left corner.

<img width="1389" alt="image" src="https://github.com/adonisjs/v5-docs/assets/380661/41cd8466-efbd-4084-8679-e167e386666d">

Expected helper link: https://v5-docs.adonisjs.com/guides/helpers

Carl

**Comment by thetutlage** [comment]
Its fixed now. Took a while :)

**Comment by carlmathisen** [comment]
Thank you, appreciate it!
