### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by Serge24** [adonisjs/v5-docs#26]
Trying to get start with database printed the message above in the terminal

**Comment by itreyoscar** [comment]
What's the version of MySQL server?

**Comment by Serge24** [comment]
Server version: 8.0.24 MySQL Community Server - GPL

**Comment by itreyoscar** [comment]
Hi @Serge24. Have you read [this](https://stackoverflow.com/a/50131831)? It solved my issue.
