### ISSUE TITLE
No reduced motion on documentation website

### ISSUE THREAD

**Issue by Arteneko** [adonisjs/v5-docs#39]
With the `prefers-reduced-motion` mode requested, the side drawers are still heavily animated.

Ideally, animations should be disabled.

**Comment by RomainLanz** [comment]
Hey!

I will have a look at it. 👍🏼

**Comment by RomainLanz** [comment]
Do you have any examples of "heavy animation" on the side drawers?

**Comment by Arteneko** [comment]
Opening and closing the side drawer.

![image](https://user-images.githubusercontent.com/23583792/125929597-8d07d30f-f3eb-4fff-b5ff-416b17522a6e.png)

**Comment by RomainLanz** [comment]
I have forgotten about the mobile view... haha.

It should be fixed this evening. 👍
