### ISSUE TITLE
link is not connected in "guides/auth/basic-auth-guard"

### ISSUE THREAD

**Issue by seonghoparkGQ** [adonisjs/v5-docs#40]
In https://docs.adonisjs.com/guides/auth/basic-auth-guard , one link is not connected. I suggest:

You can also make use of the `[auth middleware]()` to guard routes using the basic auth guard.
->
You can also make use of the `[auth middleware](./middleware.md)` to guard routes using the basic auth guard.

**Comment by RomainLanz** [comment]
Hey @seonghoparkGQ! 👋 

Could you please create a PR to fix this?
