### ISSUE TITLE
Node ace make:model not working...

### ISSUE THREAD

**Issue by josegranado** [adonisjs/v5-docs#57]
![image](https://user-images.githubusercontent.com/32282193/130372783-562961dd-84ea-43a3-b0b3-ac45b534ef22.png)

**Comment by joaovfsousa** [comment]
Hi @josegranado, have you setup Lucid yet? To create a model you should have it set as shown [in the docs](https://docs.adonisjs.com/guides/database/introduction).

**Comment by josegranado** [comment]
Yes, I setup Lucid latest version, don't work this command... It also does not appear in the list of help commands

**Comment by joaovfsousa** [comment]
Can you share your project in a public repo so I can check it?

**Comment by josegranado** [comment]
https://github.com/josegranado/hello-world, Sorry is private, but I invite you.

**Comment by josegranado** [comment]
The repository is public now. Sorry

**Comment by joaovfsousa** [comment]
You don't have Lucid setup, follow [this guide](https://docs.adonisjs.com/guides/database/introduction).
You should install lucid:
`npm i @adonisjs/lucid`
And run:
`node ace configure @adonisjs/lucid`
And then the `make:model` command will be available for you.

**Comment by thetutlage** [comment]
Closing since not actionable
