### ISSUE TITLE
AdonisJS webpack-encore DELETED my assets files

### ISSUE THREAD

**Issue by adityanurdin** [adonisjs/v5-docs#64]
![adonisjs-error](https://user-images.githubusercontent.com/37808974/131231177-9026bffb-b6b6-450f-b101-a5b267fd13a6.png)

why my assets files always deleted by webpack-encore while compiling (npm run dev) like on the pic, while creating the adonisjs project I choose "true" for configure webpack-encore. I newbie at webpack or something like that, please help me I'm so stuck here. thanks for the answer and I appreciate it. 😄😄

**Comment by thetutlage** [comment]
This is not the correct repo to ask this question. Use the github discussions to search for similar questions and then create a new discussion thread (if required)
