### ISSUE TITLE
beforePaginate hook example throws error

### ISSUE THREAD

**Issue by soizburg** [adonisjs/v5-docs#65]
### Package version
15.0.1

### Node.js and npm version
14.17.0, 6.14.3

### Issue

Trying to implement beforePaginate as the suggested solution to adonisjs/lucid#647 using the documented example at (https://docs.adonisjs.com/reference/orm/decorators#beforepaginate) 

```typescript
import { beforePaginate, BaseModel } from '@ioc:Adonis/Lucid/Orm'

class Post extends BaseModel {

  @beforePaginate()
  public static withoutSoftDeletes(query) {
    query.whereNull('deleted_at')
  }

}
```

returns the following error

`query.whereNull is not a function`

**Comment by thetutlage** [comment]
This was fixed in the docs a while ago. Please refer to the docs once again :)
