### ISSUE TITLE
Documentation for "unsigned" validation rule appears incomplete.

### ISSUE THREAD

**Issue by joshfoskett** [adonisjs/v5-docs#86]
I was looking to see if this rule exists, but the documentation for it appears to be incomplete, so I figured I'd log an issue here.

Content:
```
unsigned
NEED TO RE-THINK
```
https://docs.adonisjs.com/reference/validator/rules/unsigned

**Comment by thetutlage** [comment]
Wow! Never realised that this has made to the live website. Going to add the documentation soon

**Comment by joshfoskett** [comment]
Closing this, as it appears that this page has been removed.
